### ISSUE TITLE
New features (?)

### ISSUE THREAD

**Issue by Suburbanno** [Ryuuke/LeagueOfAndroid#2]
1 - champion's spells
2 - summoners rank (profile) and active game. (all servers)
3- items
4 - builds
5 - champion's meta
6- runes and masteries
7- skin preview
8 - free week
9 - icons preview
10 - champion's counter
11 - champion's mastery?

and the design? could use the pure material design? ( i love dashboard and FAB <3 )
And what comes to mind these days, I edit the issue..
thanks guy

**Comment by Ryuuke** [comment]
Sure it'd be great to have all of those.
For an android app, the material design is easy to implement so no worry about that, the main difficulty will be the UX part tho.
I made [a trello](https://trello.com/b/NTZW8eTs/leagueofandroid) for the features needed to be implemented within the applications, feel free to take a look.
Note that I'll be working on this at my spare time, don't expect fast iterations on the project, it'll take time, but eventually we'll have a great app in several months.

**Comment by Suburbanno** [comment]
okay, everything in its time

**Comment by Suburbanno** [comment]
@Ryuuke hey guy, news? i'm excited

**Comment by Ryuuke** [comment]
Hey @Suburbanno, 
sorry I've been busy lately, I didn't have time nor the motivation to work on the project.
Since it's open source, you can work on it too if you want to.
